### ISSUE TITLE
[FR](format): Let users control the association of language to file patterns

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_lint#107]
### What is the current behavior?

Since https://github.com/aspect-build/rules_lint/pull/105 we use the exhaustive list of file patterns from GitHub-linguist

### Describe the feature

You might want to reduce it, for example if your `BUCK` file uses typed starlark syntax, it might not work with the buildifier formatter.

**Comment by alexeagle** [comment]
Meh, this is adding to the public API surface area and no one has asked for it.

**Comment by rafikk** [comment]
I've opened a feature request in https://github.com/aspect-build/rules_lint/issues/912 which I believe addresses this use case without expanding the API surface of the ruleset.
