### ISSUE TITLE
[FR]: Add support for specifying formatter config files?

### ISSUE THREAD

**Issue by sfriedowitz** [aspect-build/rules_lint#113]
### What is the current behavior?

I am running ruff for Python following the `examples` in this repository. I configured the `multi_formatter_binary` just as in the examples, but it doesn't pick up the `ruff.toml` file located in the repo root. It seems that running a formatter via `multi_formatter_binary` does not respect config files in the repo, even after using the `ruff_aspect` as shown in the examples folder.

It looks like the aspects for linting allow you to specify configurations, but this doesn't seem to transfer over to the formatters? 

### Describe the feature

There should be a way for this to be specified for formatting, and not just linting. And if there is already a way to do this, please expand the documentation to make it clear how this is done.

**Comment by pjjw** [comment]
for the record, i handled this this with shell wrappers around the formatter tools, but that's probably not optimal.

**Comment by ewhauser** [comment]
Check out the export_files rule in the examples: https://github.com/aspect-build/rules_lint/blob/main/example/BUILD.bazel

Export the config file and it should get picked up - works for us
