### ISSUE TITLE
[FR]: Buildifier `add_tables` not supported

### ISSUE THREAD

**Issue by pullard** [aspect-build/rules_lint#149]
### What is the current behavior?

Currently there does not seem to be a way to add custom overrides to `buildifier` and am stuck with the default linting / sorting standards.

### Describe the feature

Should be able to specify the `add_tables` configuration arg to include any custom sorting enforced by the repo

```json
{
  "IsLabelArg": {},
  "LabelBlacklist": {},
  "IsSortableListArg": {},
  "SortableAllowlist": {},
  "NamePriority": {}
}
```

**Comment by alexeagle** [comment]
I think #52 is the same issue?
