### ISSUE TITLE
[Bug]: Ruff ignores excluded files/dirs when running  //:format in the  check mode

### ISSUE THREAD

**Issue by tomsoir** [aspect-build/rules_lint#170]
### What happened?

Hi!

For some reason, Ruff formatter ignores excluded files/dirs when running  `bazel run //:format -- --mode check` in the check mode only. Everything works well in fix mode `-- --mode fix`. 

<img width="1380" alt="Screenshot 2024-03-12 at 11 17 09 PM" src="https://github.com/aspect-build/rules_lint/assets/301881/6f3642c8-10e0-4f5d-a04e-15c0dda9cff5">

### Version

Development (host) and target OS/architectures: `Darwin MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64`

Output of `bazel --version`: **bazel 6.5.0**

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Other context (I use rules_lint-0.13.0 version):
```
http_archive(
    name = "aspect_rules_lint",
    sha256 = "c0824de8400f1e271c5568fc47581e165b2132f9d21691fcfefe8bf89ad413bd",
    strip_prefix = "rules_lint-0.13.0",
    url = "https://github.com/aspect-build/rules_lint/releases/download/v0.13.0/rules_lint-v0.13.0.tar.gz",
)

# Python dependencies
load("@aspect_rules_lint//lint:ruff.bzl", "fetch_ruff")

fetch_ruff()
```

Language(s) and/or frameworks involved:

Python/Ruff formatter

### How to reproduce

1. I recently added `multi_formatter_binary` where specified `python = "//tools/format:ruff",` so far only. 
```
multi_formatter_binary(
    name = "format",
    python = "//tools/format:ruff",
    # Add more languaged here...
    visibility = ["//visibility:public"],
)
```
2. In the `ruff.toml` (settings config),  has `exclude = ["main.py", "<path to /dir when main.py file located>"]` properly defined
3. Expected behavior: when I run  `bazel run //:format -- --mode check`, it should show nothing since all py files were excluded in `ruff.toml` config
4. Actual behavior: when I run  `bazel run //:format -- --mode check` it still shows 1 file that "would re-format".

**Comment by alexeagle** [comment]
This is what https://github.com/aspect-build/rules_lint/pull/70 was meant to fix. @jsharpe any idea why it's reported again?

**Comment by jsharpe** [comment]
I'm guessing the check mode needs the same flag adding to it - I only use the fix mode so didn't check the check mode.

**Comment by alexeagle** [comment]
ah yeah, of course, thanks

**Comment by tomsoir** [comment]
@alexeagle @jsharpe Thanks so much for fixing this so quickly, 
I used`git_override` to verify and everything works as expected! Thank you. 
```
git_override(
    module_name = "aspect_rules_lint",
    commit = "bb21dd2514c93876baec441cc47a48dbaacac6bf",
    remote = "https://github.com/aspect-build/rules_lint.git",
)
```
