### ISSUE TITLE
[FR]: make formatter's --mode check to be a test rule

### ISSUE THREAD

**Issue by hunshcn** [aspect-build/rules_lint#175]
### What is the current behavior?

```
bazel run //:format -- --mode check
```
we can only use `bazel run` to run check. why not make it to be a test.

Cooperating with https://github.com/aspect-build/rules_lint/issues/97 will be very helpful in ci.

### Describe the feature

```
bazel test //:format_test
```
```bazel
format_multirun_test(
    name = "format_test",
    go = "@cc_mvdan_gofumpt//:gofumpt",
    starlark = "@com_github_bazelbuild_buildtools//buildifier",
)
```

**Comment by alexeagle** [comment]
It cannot be a test because that would make a node in the dependency graph that "depends on everything in the repo".

In fact, the formatter binary doesn't even require that files to be formatted are listed as `srcs` of any Bazel target.
I suggest that CI run the formatter outside of Bazel. Note Aspect Workflows has first-class support: https://docs.aspect.build/workflows/configuration/lint

**Comment by hunshcn** [comment]
srcs is not required, wo can use a workspace arg (//:MODULE.bazel) to resolve WORKSPACE path

**Comment by hunshcn** [comment]
that's https://github.com/keith/buildifier-prebuilt do.

**Comment by hunshcn** [comment]
I think it would be cool to have all the tests in bazel test //...
And it's really possible to implement this, all ready-made, isn't it?
If you agree with me, I can implement this feature.

**Comment by alexeagle** [comment]
Bazel tests are meant to declare their inputs, so they are hermetic and can therefore be correctly cached.

**Comment by hunshcn** [comment]
Can we refer to https://github.com/bazelbuild/buildtools/pull/1092? only accept no-cache.

**Comment by hunshcn** [comment]
Working with [kazel](https://github.com/kubernetes/repo-infra/tree/master/cmd/kazel) is also a way. Then set `srcs = "//:all-files"

**Comment by hunshcn** [comment]
> Can we refer to [bazelbuild/buildtools#1092](https://github.com/bazelbuild/buildtools/pull/1092)? only accept no-cache.



> Working with [kazel](https://github.com/kubernetes/repo-infra/tree/master/cmd/kazel) is also a way. Then set `srcs = "//:all-files"`
> 
> Of course, this also has a disadvantage (you need to add an additional kazel test (no-cache)).
> 
> This is implemented as [hack/verify-bazel.sh](https://github.com/kubernetes/repo-infra/blob/master/hack/verify-bazel.sh) and [hack/update-bazel.sh](https://github.com/kubernetes/repo-infra/blob/master/hack/update-bazel.sh) in [repo-infra](https://github.com/kubernetes/repo-infra).

I don't know if you can see the above information, so ping @alexeagle

**Comment by alexeagle** [comment]
Interesting, thanks for the link to `no_sandbox = True` on buildifier_test. (And similar on https://github.com/keith/buildifier-prebuilt/blob/main/buildifier/factory.bzl#L69)
I'm still not sure it's desirable to introduce a test that is always going to have run the formatter over all the files in the repository. Only changed files need to be checked, and so encouraging anyone to set it up this way feels like a way to make a slow developer experience.

**Comment by hunshcn** [comment]
> Interesting, thanks for the link to `no_sandbox = True` on buildifier_test. (And similar on https://github.com/keith/buildifier-prebuilt/blob/main/buildifier/factory.bzl#L69) I'm still not sure it's desirable to introduce a test that is always going to have run the formatter over all the files in the repository. Only changed files need to be checked, and so encouraging anyone to set it up this way feels like a way to make a slow developer experience.

Buildifier_test can run in `no_sandbox` mode (no-cache) or specify srcs to run (achieve the same effect with kazel).

This gives users two choices. If the performance is sensitive, working with kazel is a good idea, evenif`kazel.check` can not be cached too. If not, using `no_sandbox` is more convenient.
Because linter(no-cached) may spend a lot of time, but kazel won't, it is very simple.

**Comment by hunshcn** [comment]
so can we reopen this issue? @alexeagle

**Comment by alexeagle** [comment]
I'm okay with taking a PR to behave similarly to buildifier_test.
