### ISSUE TITLE
[FR]: Kotlin linter

### ISSUE THREAD

**Issue by smocherla-brex** [aspect-build/rules_lint#212]
### What is the current behavior?

There's no support for Kotlin linting with rules_lint right now, but I thought'd be really nice if either ktlint (https://github.com/pinterest/ktlint) and/or detekt (https://github.com/detekt/detekt). While rules_kotlin has support for ktlint, it lacks many other configuration options like a custom ruleset jar for ktlint, and in general I really like the approach of rules_lint using aspects rather than their dedicated targets which we need to run as tests separately.

### Describe the feature

Currently, no linter support is documented with Kotlin with rules_lint. We use Kotlin heavily at our company and it would be nice to plugin in rules_lint for this. I'm happy to spend cycles to put together PRs for this if it's something you'd be interested in accepting as a contribution.

**Comment by alexeagle** [comment]
Absolutely we'd like to take a PR for this, please let me know if contributor docs need work.

**Comment by smocherla-brex** [comment]
https://github.com/aspect-build/rules_lint/pull/215 is an attempt at adding support for ktlint.

**Comment by alexeagle** [comment]
Done in #215 thanks!
