### ISSUE TITLE
[Bug]: Include transitive declarations with eslint inputs

### ISSUE THREAD

**Issue by sallustfire** [aspect-build/rules_lint#335]
### What happened?

The lint_eslint_aspect does not include type information and reports errors about the misuse of any when the typescript-eslint plugin rules tseslint.configs.recommendedTypeChecked are enabled.

### Version

Development (host) and target OS/architectures: Pop!_OS 22.04 LTS

Output of `bazel --version`: 7.1.1

### Any other information?

While `gather_files_from_js_infos` is used, the sources are retrieved from the target as files and not JsInfo, so no transitive dependencies are inclluded. Fixing this requires getting the JsInfo provide from the target in the aspect implementation.

**Comment by alexeagle** [comment]
This would be great to fix before 1.0.0 final - I'll hold the release a bit longer :)
