### ISSUE TITLE
[FR]: Add C file support for clang-format.

### ISSUE THREAD

**Issue by agoessling** [aspect-build/rules_lint#350]
### What is the current behavior?

C files (`*.c`) are not formatted.

### Describe the feature

Use `clang-format` to format `*.c` files.  I have a PR (#349) that does this, but I'm not sure if my change is the cleanest given how `format.sh` is manually populated from the output of `mirror_linguist_languages.sh`.  One would need to remember to add `*.c` after doing so.  I don't know anything about `jq` so I figured someone else might be able to suggest the clean way to do this.

**Comment by alexeagle** [comment]
fixed by #349
