### ISSUE TITLE
[Bug]: Undeclared dependence on bazel-lib 2.7.7

### ISSUE THREAD

**Issue by agoessling** [aspect-build/rules_lint#351]
### What happened?

The `clang-tidy` aspect contains an undeclared dependency on `bazel-lib` 2.7.7 (or at least one >2.5.0).  If you pare the `example` module down to just the `clang-tidy` relevant code, you technically don't need to depend on `bazel-lib` directly, but when you remove this dependency the version in `rules_lint` (2.5.0) is insufficient.  If you change the dependency in `rules_lint` to 2.7.7, things work as expected.

### Version

Development (host) and target OS/architectures: linux x86

Output of `bazel --version`: bazel 7.2.1

Language(s) and/or frameworks involved: C/C++ clang-tidy

### How to reproduce

```shell
1. Clone this branch: https://github.com/agoessling/rules_lint/tree/bazel_lib_dep
2. `cd rules_lint/example`
3. `bazel build --aspects=//tools/lint:linters.bzl%clang_tidy --output_groups=rules_lint_human src:hello_c && cat bazel-bin/src/hello_c.AspectRulesLintClangTidy.out`
4. change `bazel-lib` dep to 2.7.7 in `rules_lint/MODULE.bazel`
5. `bazel build --aspects=//tools/lint:linters.bzl%clang_tidy --output_groups=rules_lint_human src:hello_c && cat bazel-bin/src/hello_c.AspectRulesLintClangTidy.out`
```

**Comment by alexeagle** [comment]
I guess you're using WORKSPACE and not bzlmod, since the MODULE.bazel file in this repo already has a minimum of bazel-lib 2.5.0. See #354

**Comment by agoessling** [comment]
I don't think so, [the reproduction branch](https://github.com/agoessling/rules_lint/tree/bazel_lib_dep/example) I linked above doesn't even have a WORKSPACE file, only MODULE.bazel: 
![image](https://github.com/user-attachments/assets/6bade5f2-4614-4a24-a1d2-4534e7bef96a)

**Comment by agoessling** [comment]
Also note, the required dependency is >2.5.0,  2.5.0 is in the MODULE.bazel file and it doesn't work.

**Comment by agoessling** [comment]
@alexeagle I'm not sure this should be closed.  Did you take a look at [the branch](https://github.com/agoessling/rules_lint/tree/bazel_lib_dep/example) that is reproducing this issue?  It is using bzlmod.  The issue isn't with [not having 2.5.0](https://github.com/agoessling/rules_lint/blob/bazel_lib_dep/MODULE.bazel#L10), 2.5.0 is not enough.  2.7.7 makes it work.  Note: rules_lint contains [an override](https://github.com/agoessling/rules_lint/blob/bazel_lib_dep/MODULE.bazel#L34) to 2.7.7.  Sorry I haven't done a good job explaining the issue.  The reproduction steps above are probably the best way to demonstrate the problem.
