### ISSUE TITLE
[Bug]: ruff integration / version pinning docs don't work with bazel run

### ISSUE THREAD

**Issue by novas0x2a** [aspect-build/rules_lint#389]
### What happened?

The docs describe [this method](https://github.com/aspect-build/rules_lint/blob/981909c9053b66f90a4cf22a05f90f5673fe9996/docs/ruff.md?plain=1#L30) of integrating ruff. Unfortunately, this has a problem: the host platform constraint is not applied to the ruff target itself, meaning, `bazel run --platform not_my_host_plat :ruff` will run the wrong ruff.

A naive fix doesn't really work very well either:
```
platform_transition_binary(
    name = "ruff",
    binary = ":ruff_raw", # same as the alias in the docs
    target_platform = "@local_config_platform//:host",
    visibility = ["//visibility:public"],
)
```

The problem with this approach is the transitioned binary doesn't have the same working directory; for example, this approach means you have to run `bazel run :ruff -- $PWD/path/to thing` instead of `bazel run :ruff -- path/to thing`.

Another approach is to create a bunch of config_settings that select on `host_cpu`, but that seems very ugly.

### Version

Development (host) and target OS/architectures: host=linux, target=various

Output of `bazel --version`: bazel 7.3.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: This is from the docs at current HEAD.

Language(s) and/or frameworks involved:

**Comment by alexeagle** [comment]
I think this documentation is only intended to get ruff running on the host platform. What's your use case for wanting to run it for a non-host platform?

**Comment by alexeagle** [comment]
From slack - we determined that the multitool install of ruff is what you really wanted. I should change all the documentation to use that.
