### ISSUE TITLE
[Bug]: lint_stylelint_aspect does not include config dependencies

### ISSUE THREAD

**Issue by sallustfire** [aspect-build/rules_lint#394]
### What happened?

In analogy with eslint, the typical setup for the stylelint config file is to copy it to the output tree as a js_library. The config file may depend on external stylelint plugins which need to be made available via runfiles. The implementation only declares a dependency on the config file and does not include the config file's dependencies.

### Version

Development (host) and target OS/architectures: Pop!_OS 22.04 LTS

Output of `bazel --version`: 7.1.1

Language(s) and/or frameworks involved: stylelint

### How to reproduce

```shell
Add extends to the stylelint config or depend on a plugin.
```

**Comment by alexeagle** [comment]
fixed by #395
