### ISSUE TITLE
[Bug]: scalafmt stopped working in 1.0.0-rc9

### ISSUE THREAD

**Issue by agluszak** [aspect-build/rules_lint#413]
### What happened?

It works in 1.0.0-rc8. Starting in 1.0.0-rc9 it reports progress as usual, but the changes to the files are not made. Same in 1.0.0-rc10, 1.0.1 and 1.0.2

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:
bazel 7.3.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by alexeagle** [comment]
That's very surprising - studying https://github.com/aspect-build/rules_lint/compare/v1.0.0-rc8...v1.0.0-rc9 I can't see anything that could explain this.
Also I edited `example/src/hello.scala`  in this repo and then `cd example ; bazel run format src/hello.scala` and it re-formatted the file.

So I think something else must be wrong in your setup.

**Comment by hb-man** [comment]
> That's very surprising - studying [v1.0.0-rc8...v1.0.0-rc9](https://github.com/aspect-build/rules_lint/compare/v1.0.0-rc8...v1.0.0-rc9) I can't see anything that could explain this. Also I edited `example/src/hello.scala` in this repo (at HEAD) and then `cd example ; bazel run format src/hello.scala` and it re-formatted the file.
> 
> So I think something else must be wrong in your setup.

I'll try independently reproduce this in our setup in a couple of days and will give more info.

**Comment by alexeagle** [comment]
please re-open or re-file if you do find there's a rules_lint bug!
