### ISSUE TITLE
[Bug]: aspect_rules_lint 0.5.0 doesn't exists on registry.bazel.build

### ISSUE THREAD

**Issue by minglei-pony** [aspect-build/rules_lint#54]
### What happened?

https://registry.bazel.build/modules/aspect_rules_lint
aspect_rules_lint 0.5.0 doesn't exists on registry.bazel.build

### Version

---

**Comment by alexeagle** [comment]
It was a mistake https://github.com/bazelbuild/bazel-central-registry/pull/1081#issuecomment-1788306034

later versions do appear on the registry.
