### ISSUE TITLE
[FR]: Run buildifier lint as a formatter

### ISSUE THREAD

**Issue by ewhauser** [aspect-build/rules_lint#57]
### What is the current behavior?

buildifier runs as a formatter currently, but bulidfier [lint](https://chromium.googlesource.com/external/github.com/bazelbuild/buildtools/+/HEAD/buildifier/README.md#linter) doesn't run. Because `rules_lint` uses aspects to run lint mode, it wouldn't make sense to try to run buildifier as a linter.

### Describe the feature

Suggestion: add an optional `buildifer_lint` to the multi formatter. Even though it is technically a linter vs a formatter, this seems reasonable sense it is opt in. Happy to submit a PR for this.

**Comment by alexeagle** [comment]
The developer experience of running our multi_formatter_binary doesn't provide any affordance for it to print things. We always throw away the stdout/stderr and there's no way to present findings to the user. I don't think jamming a linter into the formatter binary will work well.

There's a gazelle extension in skylib to produce `bzl_library` rules for all `.bzl` files, and we could lint those targets. I wonder if that's good enough - it misses linting `BUILD.bazel` files though.

**Comment by ewhauser** [comment]
That would be problematic. I've never had buildifier lint mode come across something that it can't auto fix though - not sure if that is possible? We run it on pre-commit and I've never fixed anything by hand.

**Comment by alexeagle** [comment]
That's not been my experience. Every time I enable buildifier lint for a repo, there is a bunch of manual fixing required, like missing docstring args, missing module doc, etc.

https://github.com/p0deje/rules_ruby/commit/b13ded4fbeae1301444a7c9c5da7f8b3dfecea70
https://github.com/bazelbuild/rules_pkg/pull/776/files

**Comment by ewhauser** [comment]
Ah, it appears our pre-commit scripts runs in lint fix mode so it is only catching what can be fixed automatically

**Comment by alexeagle** [comment]
Yeah that makes sense, I always found these modes confusing

**Comment by alexeagle** [comment]
My sense is that we just can't lint BUILD files because there are no `*_library` targets that gather their `srcs`.

**Comment by ewhauser** [comment]
Agree
