### ISSUE TITLE
[Bug]: eslint test doesn't work when passing transpiler to ts_project

### ISSUE THREAD

**Issue by MaartenStaa** [aspect-build/rules_lint#74]
### What happened?

We're using `ts_project` from Aspect's `rules_ts`, and passing in `swc` as a transpiler:

```starlark
ts_project(
    name = name,
    srcs = srcs,
    transpiler = partial.make(
        swc,
        source_maps = "true",
        swcrc = swcrc,
    ),
    source_map = True,
    resolve_json_module = True,
    allow_js = False,
    incremental = True,
    declaration = True,
    tsconfig = tsconfig,
    deps = deps,
    **kwargs
)
```

Creating a lint target based on this `name`, results in linting the `.js` and `.js.map` files generated by SWC. If instead we pass in the `:<name>_transpile` target that `rules_ts` generates for SWC, we get the following error:

```
ERROR: <snip>/BUILD.bazel:10:26: in _eslint_test rule //foo/bar:baz.lint:
Traceback (most recent call last):
        File "<sandbox>/external/aspect_rules_lint/lint/lint_test.bzl", line 43, column 43, in _test_impl
                for report in src[OutputGroupInfo].rules_lint_report.to_list():
Error: 'OutputGroupInfo' value has no field or method 'rules_lint_report'
Available attributes: _hidden_top_level_INTERNAL_
```

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: bazel 6.3.1-0c22e4f

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
- `rules_lint`: 0.6.1
- `rules_ts`: 2.0.1

Language(s) and/or frameworks involved:
- Typescript

**Comment by alexeagle** [comment]
Yup, it's a bit confusing, I ran into this too.
The linter will find `.ts` sources on the `ts_project` target, but with the `transpiler` bit, the macro expansion is laid out like so:
https://github.com/aspect-build/rules_ts/blob/main/docs/transpiler.md#macro-expansion

So you want to use the `[name]_typecheck` rule as the `srcs` of the `eslint_test`.

**Comment by alexeagle** [comment]
Here's an example: https://github.com/bazelbuild/examples/blob/main/frontend/react/src/BUILD.bazel#L86-L92
