### ISSUE TITLE
[Bug]: shfmt doesn't respect editorconfig-defined ignored files

### ISSUE THREAD

**Issue by ciarand** [aspect-build/rules_lint#80]
### What happened?

I have a file in my vendor'd `third_party` directory. There's a shell script in that directory that's not correctly formatted. Normally, I'd be able to instruct the `shfmt` tool to ignore that directory by setting up an `.editorconfig` file that looks like this:

```
# Ignore the entire "third_party" directory.
[third_party/**]
ignore = true
```

This is described in the [`shfmt` documentation](https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd).

Unfortunately, the `shfmt` tool only applies this `ignore` setting when it's being passed a directory to walk. When passed a list of filenames directly, `shfmt` formats the files with no regard to the `ignore` setting. This is an [open issue](https://github.com/mvdan/sh/issues/1037) on the `shfmt`'s bug tracker, but the author feels that the tool's behavior is correct.

### Version

Development (host) and target OS/architectures:

Linux / amd64

Output of `bazel --version`:

6.2.1

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

v0.7.0

Language(s) and/or frameworks involved:

shfmt

### How to reproduce

1. Create a misformatted shell file in `third_party/bad.sh`:

```shell
#!/usr/bin/env bash

      function     badly_formatted()    {
  true
}
```

2. Ask `shfmt` to ignore it by adding an `.editorconfig` file:

```
# .editorconfig
[third_party/**]
ignore = true
```

3. Run the `//:format` target

Expected results: `third_party/bad.sh` isn't changed

Actual results: `third_party/bad.sh` is reformatted

**Comment by ciarand** [comment]
Ah, sorry, I forgot to finish my thought. This might just be a feature request for a rules_lint ignore list / function to prevent these files from being passed to (at least) the `shfmt` binary, but I marked it as a bug because the behavior looks akin to a bug even if both systems are sort-of doing some definition of the right thing

**Comment by alexeagle** [comment]
Thanks for pointing to the black --force-exclude as a precedent on that issue. I agree that's the desirable fix here.

I think you could also make the case that pre-commit hooks will fall into the same trap - pre-commit.com is pretty popular FWICT, does it have this bug too?
