### ISSUE TITLE
[Bug]: markdown support doesn't seem to be implemented

### ISSUE THREAD

**Issue by saada** [aspect-build/rules_lint#81]
### What happened?

Tried using `markdown` in the `multi_formatter_binary` and got an error

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `bazel 6.4.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
multi_formatter_binary(
    name = "format",

    markdown = ":prettier"
)
```

throws

```
ERROR: <REDACTED>/BUILD:54:23: //:format: no such attribute 'markdown' in 'multi_formatter_binary' rule
```

### Any other information?

The docs clearly state markdown is supported using Prettier but the rule doesn't expose that option

**Comment by alexeagle** [comment]
Yeah, this is confusing - we include `*.md` when running prettier:
https://github.com/aspect-build/rules_lint/blob/main/format/private/format.sh#L92-L96
but you have to use the `javascript = ":prettier"` setting in `multi_formatter_binary` to enable that, even if you have no JavaScript.

**Comment by alexeagle** [comment]
Fixed by https://github.com/aspect-build/rules_lint/commit/6ea66fb4c7b653f8e061d0997bfb74f965609835
