### ISSUE TITLE
[FR]: formatter's --mode check shouldn't bail on the first error

### ISSUE THREAD

**Issue by ciarand** [aspect-build/rules_lint#97]
### What is the current behavior?

I've defined `//:format` as a `multi_formatter_binary` that supports Go, Starlark, and Java. I have a Go file and a Java file which are both incorrectly formatted. Running `bazel run //:format -- --mode check` prints the following output:

```
Formatting Starlark with Buildifier...
Formatting Java with java-format...
java/com/.../SomeJavaFile.java
java/com/.../SomeJavaFile.java
FAILED: A formatter tool exited with code 123
Try running 'bazel run @@//bazel/lint:format' to fix this.
```

Notice that the check didn't reach the Go file, it bailed after the first error.

### Describe the feature

It would be helpful for usability reasons if the `--mode check` invocation of the formatter checked *all* the file types and reported an exhaustive list of unformatted files.

**Comment by alexeagle** [comment]
Sounds good to me - probably at the same time it makes sense to fix a TODO in there to run the formatter tools in parallel as well (both in check and fix mode)
